version: "3"

services:
  app:
    container_name: urlshortener
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 0
      REDIS_HOST: redis
    ports:
      - 5000:5000

  redis:
    container_name: cache
    image: redis:6-alpine
